version: '3'

services:
  app:
    container_name: laravel_container
    image: ryanc-laravel
    ports:
      - "80:80" 
    depends_on:
      - db 
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 
  db:
    image: mysql   #always pull the latest mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./db_data:/var/lib/mysql  
