name: Deploy to ECR and Test

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Amazon ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your region

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-laravel-app .
      
      # Tag Docker image with ECR repository
      - name: Tag Docker image
        run: |
          docker tag my-laravel-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/my-laravel-app:latest
      
      # Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/my-laravel-app:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/my-laravel-app:latest

      - name: Run Docker container
        run: |
          docker run -d --name my-laravel-container ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/my-laravel-app:latest
      
      - name: Check container status
        run: |
          container_status=$(docker inspect -f '{{.State.Status}}' my-laravel-container)
          if [[ $container_status == "running" ]]; then
            echo "Container status: $container_status - Success"
          else
            echo "Container status: $container_status - Failure"
            exit 1
          fi
